# Basic configuration for experiments and pipeline
data:
  csv_path: data/raw/sales.csv

experiments:
  default_param_grid:
    est__hidden_layer_sizes: [[32], [64], [32, 16]]
    est__alpha: [0.0001, 0.001]
    est__learning_rate_init: [0.001, 0.0001]
